{{- $resourceMeta := default (dict) .Values.resourceMeta }}
{{- $arsMeta := and .Values.resourceMeta .Values.resourceMeta.autoscalingRunnerSet }}
{{- $containerMode := .Values.containerMode }}
{{- $tlsConfig := (default (dict) .Values.githubServerTLS) }}
{{- if or (not (include "gha-runner-scale-set.scale-set-name" .)) (gt (len (include "gha-runner-scale-set.scale-set-name" .)) 45) }}
{{ fail "Name must have up to 45 characters" }}
{{- end }}
{{- if gt (len (include "gha-runner-scale-set.namespace" .)) 63 }}
{{ fail "Namespace must have up to 63 characters" }}
{{- end }}
{{- $annotations := include "gha-runner-scale-set.effective-annotations" (dict "ctx" . "meta" $arsMeta "strict" true) | fromJson }}
{{- $_ := set $annotations "actions.github.com/values-hash" (toJson .Values | sha256sum | trunc 63) }}
{{- if not (kindIs "string" .Values.githubConfigSecret) }}
{{- $_ := set $annotations "actions.github.com/cleanup-github-secret-name" (include "gha-runner-scale-set.githubsecret" .) }}
{{- end }}
{{- $_ := set $annotations "actions.github.com/cleanup-manager-role-binding" (include "gha-runner-scale-set.managerRoleBindingName" .) }}
{{- $_ := set $annotations "actions.github.com/cleanup-manager-role-name" (include "gha-runner-scale-set.managerRoleName" .) }}
{{- if and (or (eq $containerMode.type "kubernetes") (eq $containerMode.type "kubernetes-novolume")) (not .Values.template.spec.serviceAccountName) }}
{{- $_ := set $annotations "actions.github.com/cleanup-kubernetes-mode-role-binding-name" (include "gha-runner-scale-set.kubeModeRoleBindingName" .) }}
{{- $_ := set $annotations "actions.github.com/cleanup-kubernetes-mode-role-name" (include "gha-runner-scale-set.kubeModeRoleName" .) }}
{{- $_ := set $annotations "actions.github.com/cleanup-kubernetes-mode-service-account-name" (include "gha-runner-scale-set.kubeModeServiceAccountName" .) }}
{{- end }}
{{- if and (ne $containerMode.type "kubernetes") (ne $containerMode.type "kubernetes-novolume") (not .Values.template.spec.serviceAccountName) }}
{{- $_ := set $annotations "actions.github.com/cleanup-no-permission-service-account-name" (include "gha-runner-scale-set.noPermissionServiceAccountName" .) }}
{{- end }}
apiVersion: "actions.github.com/v1alpha1"
kind: "AutoscalingRunnerSet"
metadata: {
  name: {{ include "gha-runner-scale-set.scale-set-name" . | replace "_" "-" | toJson }},
  namespace: {{ include "gha-runner-scale-set.namespace" . | toJson }},
  labels: {{ include "gha-runner-scale-set.effective-labels" (dict "ctx" . "meta" $arsMeta "strict" true "component" "autoscaling-runner-set") }},
  annotations: {{ $annotations | toJson }},
}
spec: {
  githubConfigUrl: {{ required ".Values.githubConfigUrl is required" (trimSuffix "/" .Values.githubConfigUrl) | toJson }},
  githubConfigSecret: {{ include "gha-runner-scale-set.githubsecret" . | toJson }},
  {{- with .Values.runnerGroup }}
  runnerGroup: {{ . | toJson }},
  {{- end }}
  {{- with .Values.runnerScaleSetName }}
  runnerScaleSetName: {{ . | toJson }},
  {{- end }}
  {{- if and .Values.scaleSetLabels (kindIs "slice" .Values.scaleSetLabels) }}
  {{- range .Values.scaleSetLabels }}
  {{- if empty . }}
  {{- fail "scaleSetLabels contains an empty string, each label must be a non-empty string of less than 256 characters" }}
  {{- end }}
  {{- if ge (len .) 256 }}
  {{- fail "scaleSetLabels contains a label that is 256 characters or more, each label must be a non-empty string of less than 256 characters" }}
  {{- end }}
  {{- end }}
  runnerScaleSetLabels: {{ .Values.scaleSetLabels | toJson }},
  {{- end }}
  {{- if .Values.githubServerTLS }}
  githubServerTLS: {
    {{- with .Values.githubServerTLS.certificateFrom }}
    certificateFrom: {
      configMapKeyRef: {
        name: {{ .configMapKeyRef.name | toJson }},
        key: {{ .configMapKeyRef.key | toJson }},
      },
    },
    {{- end }}
  },
  {{- end }}
  {{- if and .Values.keyVault .Values.keyVault.type }}
  vaultConfig: {
    type: {{ .Values.keyVault.type | toJson }},
    {{- if .Values.keyVault.proxy }}
    proxy: {{ .Values.keyVault.proxy | toJson }},
    {{- end }}
    {{- if eq .Values.keyVault.type "azure_key_vault" }}
    azureKeyVault: {
      url: {{ .Values.keyVault.azureKeyVault.url | toJson }},
      tenantId: {{ .Values.keyVault.azureKeyVault.tenantId | toJson }},
      clientId: {{ .Values.keyVault.azureKeyVault.clientId | toJson }},
      certificatePath: {{ .Values.keyVault.azureKeyVault.certificatePath | toJson }},
      secretKey: {{ .Values.keyVault.azureKeyVault.secretKey | toJson }},
    },
    {{- else }}
    {{- fail "Unsupported keyVault type: " .Values.keyVault.type }}
    {{- end }}
  },
  {{- end }}
  {{- if .Values.proxy }}
  proxy: {
    {{- if .Values.proxy.http }}
    http: {
      url: {{ .Values.proxy.http.url | toJson }},
      {{- if .Values.proxy.http.credentialSecretRef }}
      credentialSecretRef: {{ .Values.proxy.http.credentialSecretRef | toJson }},
      {{- end }}
    },
    {{- end }}
    {{- if .Values.proxy.https }}
    https: {
      url: {{ .Values.proxy.https.url | toJson }},
      {{- if .Values.proxy.https.credentialSecretRef }}
      credentialSecretRef: {{ .Values.proxy.https.credentialSecretRef | toJson }},
      {{- end }}
    },
    {{- end }}
    {{- if and .Values.proxy.noProxy (kindIs "slice" .Values.proxy.noProxy) }}
    noProxy: {{ .Values.proxy.noProxy | toJson }},
    {{- end }}
  },
  {{- end }}
  {{- if and (or (kindIs "int64" .Values.minRunners) (kindIs "float64" .Values.minRunners)) (or (kindIs "int64" .Values.maxRunners) (kindIs "float64" .Values.maxRunners)) }}
  {{- if gt .Values.minRunners .Values.maxRunners }}
  {{- fail "maxRunners has to be greater or equal to minRunners" }}
  {{- end }}
  {{- end }}
  {{- if or (kindIs "int64" .Values.maxRunners) (kindIs "float64" .Values.maxRunners) }}
  {{- if lt (.Values.maxRunners | int) 0 }}
  {{- fail "maxRunners has to be greater or equal to 0" }}
  {{- end }}
  maxRunners: {{ .Values.maxRunners | int }},
  {{- end }}
  {{- if or (kindIs "int64" .Values.minRunners) (kindIs "float64" .Values.minRunners) }}
  {{- if lt (.Values.minRunners | int) 0 }}
  {{- fail "minRunners has to be greater or equal to 0" }}
  {{- end }}
  minRunners: {{ .Values.minRunners | int }},
  {{- end }}
  {{- with .Values.listenerTemplate }}
  listenerTemplate: {{ . | toJson }},
  {{- end }}
  {{- with .Values.listenerMetrics }}
  listenerMetrics: {{ . | toJson }},
  {{- end }}
  {{- with (index $resourceMeta "autoscalingListener") }}
  autoscalingListener: {{ include "gha-runner-scale-set.resourceMetaSpec" . }},
  {{- end }}
  {{- with (index $resourceMeta "listenerServiceAccount") }}
  listenerServiceAccountMetadata: {{ include "gha-runner-scale-set.resourceMetaSpec" . }},
  {{- end }}
  {{- with (index $resourceMeta "listenerRole") }}
  listenerRoleMetadata: {{ include "gha-runner-scale-set.resourceMetaSpec" . }},
  {{- end }}
  {{- with (index $resourceMeta "listenerRoleBinding") }}
  listenerRoleBindingMetadata: {{ include "gha-runner-scale-set.resourceMetaSpec" . }},
  {{- end }}
  {{- with (index $resourceMeta "listenerConfigSecret") }}
  listenerConfigSecretMetadata: {{ include "gha-runner-scale-set.resourceMetaSpec" . }},
  {{- end }}
  {{- with (index $resourceMeta "ephemeralRunnerSet") }}
  ephemeralRunnerSetMetadata: {{ include "gha-runner-scale-set.resourceMetaSpec" . }},
  {{- end }}
  {{- with (index $resourceMeta "ephemeralRunner") }}
  ephemeralRunnerMetadata: {{ include "gha-runner-scale-set.resourceMetaSpec" . }},
  {{- end }}
  {{- with (index $resourceMeta "ephemeralRunnerConfigSecret") }}
  ephemeralRunnerConfigSecretMetadata: {{ include "gha-runner-scale-set.resourceMetaSpec" . }},
  {{- end }}
  template: {
    {{- with .Values.template.metadata }}
    metadata: {
      {{- with .labels }}
      labels: {{ . | toJson }},
      {{- end }}
      {{- with .annotations }}
      annotations: {{ . | toJson }},
      {{- end }}
    },
    {{- end }}
    spec: {
      {{- range $key, $val := .Values.template.spec }}
      {{- if and (ne $key "containers") (ne $key "volumes") (ne $key "initContainers") (ne $key "serviceAccountName") }}
      {{ $key }}: {{ $val | toJson }},
      {{- end }}
      {{- end }}
      {{- if not .Values.template.spec.restartPolicy }}
      restartPolicy: "Never",
      {{- end }}
      {{- if or (eq $containerMode.type "kubernetes") (eq $containerMode.type "kubernetes-novolume") }}
      serviceAccountName: {{ default (include "gha-runner-scale-set.kubeModeServiceAccountName" .) .Values.template.spec.serviceAccountName | toJson }},
      {{- else }}
      serviceAccountName: {{ default (include "gha-runner-scale-set.noPermissionServiceAccountName" .) .Values.template.spec.serviceAccountName | toJson }},
      {{- end }}
      {{- if or .Values.template.spec.initContainers (eq $containerMode.type "dind") }}
      initContainers: [
        {{- if eq $containerMode.type "dind" }}
        {{ include "gha-runner-scale-set.dind-init-container" . }},
        {{- if (ge (.Capabilities.KubeVersion.Minor | int) 29) }}
        {{ include "gha-runner-scale-set.dind-container" . }},
        {{- end }}
        {{- end }}
        {{- range .Values.template.spec.initContainers }}
        {{ . | toJson }},
        {{- end }}
      ],
      {{- end }}
      containers: [
        {{- if eq $containerMode.type "dind" }}
        {{ include "gha-runner-scale-set.dind-runner-container" . }},
        {{- if not (ge (.Capabilities.KubeVersion.Minor | int) 29) }}
        {{ include "gha-runner-scale-set.dind-container" . }},
        {{- end }}
        {{- include "gha-runner-scale-set.non-runner-non-dind-containers" . | nindent 8 }}
        {{- else if eq $containerMode.type "kubernetes" }}
        {{ include "gha-runner-scale-set.kubernetes-mode-runner-container" . }},
        {{- include "gha-runner-scale-set.non-runner-containers" . | nindent 8 }}
        {{- else if eq $containerMode.type "kubernetes-novolume" }}
        {{ include "gha-runner-scale-set.kubernetes-novolume-mode-runner-container" . }},
        {{- include "gha-runner-scale-set.non-runner-containers" . | nindent 8 }}
        {{- else }}
        {{- include "gha-runner-scale-set.default-mode-runner-containers" . | nindent 8 }}
        {{- end }}
      ],
      {{- if or .Values.template.spec.volumes (eq $containerMode.type "dind") (eq $containerMode.type "kubernetes") $tlsConfig.runnerMountPath }}
      volumes: [
        {{- if $tlsConfig.runnerMountPath }}
        {{- include "gha-runner-scale-set.tls-volume" $tlsConfig | nindent 8 }}
        {{- end }}
        {{- if eq $containerMode.type "dind" }}
        {{- include "gha-runner-scale-set.dind-volume" . | nindent 8 }}
        {{- include "gha-runner-scale-set.dind-work-volume" . | nindent 8 }}
        {{- include "gha-runner-scale-set.non-work-volumes" . | nindent 8 }}
        {{- else if eq $containerMode.type "kubernetes" }}
        {{- include "gha-runner-scale-set.kubernetes-mode-work-volume" . | nindent 8 }}
        {{- include "gha-runner-scale-set.non-work-volumes" . | nindent 8 }}
        {{- else }}
        {{- range .Values.template.spec.volumes }}
        {{ . | toJson }},
        {{- end }}
        {{- end }}
      ],
      {{- else if eq $containerMode.type "kubernetes-novolume" }}
      volumes: [],
      {{- end }}
    },
  },
}
