{{- $containerMode := .Values.containerMode }}
{{- $meta := and .Values.resourceMeta .Values.resourceMeta.kubernetesModeRoleBinding }}
{{- if and (or (eq $containerMode.type "kubernetes") (eq $containerMode.type "kubernetes-novolume")) (not .Values.template.spec.serviceAccountName) }}
{{- $annotations := include "gha-runner-scale-set.effective-annotations" (dict "ctx" . "meta" $meta) | fromJson }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata: {
  name: {{ include "gha-runner-scale-set.kubeModeRoleBindingName" . | toJson }},
  namespace: {{ include "gha-runner-scale-set.namespace" . | toJson }},
  labels: {{ include "gha-runner-scale-set.effective-labels" (dict "ctx" . "meta" $meta) }},
  {{- if $annotations }}
  annotations: {{ $annotations | toJson }},
  {{- end }}
  finalizers: ["actions.github.com/cleanup-protection"],
}
roleRef: {
  apiGroup: "rbac.authorization.k8s.io",
  kind: "Role",
  name: {{ include "gha-runner-scale-set.kubeModeRoleName" . | toJson }},
}
subjects: [{
  kind: "ServiceAccount",
  name: {{ include "gha-runner-scale-set.kubeModeServiceAccountName" . | toJson }},
  namespace: {{ include "gha-runner-scale-set.namespace" . | toJson }},
}]
{{- end }}
