{{- $containerMode := .Values.containerMode }}
{{- $meta := and .Values.resourceMeta .Values.resourceMeta.kubernetesModeRole }}
{{- if and (or (eq $containerMode.type "kubernetes") (eq $containerMode.type "kubernetes-novolume")) (not .Values.template.spec.serviceAccountName) }}
{{- $annotations := include "gha-runner-scale-set.effective-annotations" (dict "ctx" . "meta" $meta) | fromJson }}
# default permission for runner pod service account in kubernetes mode (container hook)
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata: {
  name: {{ include "gha-runner-scale-set.kubeModeRoleName" . | toJson }},
  namespace: {{ include "gha-runner-scale-set.namespace" . | toJson }},
  labels: {{ include "gha-runner-scale-set.effective-labels" (dict "ctx" . "meta" $meta) }},
  {{- if $annotations }}
  annotations: {{ $annotations | toJson }},
  {{- end }}
  finalizers: ["actions.github.com/cleanup-protection"],
}
rules: [{
  apiGroups: [""],
  resources: ["pods"],
  verbs: ["get", "list", "create", "delete"],
}, {
  apiGroups: [""],
  resources: ["pods/exec"],
  verbs: ["get", "create"],
}, {
  apiGroups: [""],
  resources: ["pods/log"],
  verbs: ["get", "list", "watch"],
},
{{- if ne $containerMode.type "kubernetes-novolume" }}
{
  apiGroups: ["batch"],
  resources: ["jobs"],
  verbs: ["get", "list", "create", "delete"],
},
{{- end }}
{
  apiGroups: [""],
  resources: ["secrets"],
  verbs: ["get", "list", "create", "delete"],
},
{{- range $containerMode.kubernetesModeAdditionalRoleRules }}
{{ . | toJson }},
{{- end }}
]
{{- end }}
