{{- $containerMode := .Values.containerMode }}
{{- $meta := and .Values.resourceMeta .Values.resourceMeta.kubernetesModeServiceAccount }}
{{- if and (or (eq $containerMode.type "kubernetes") (eq $containerMode.type "kubernetes-novolume")) (not .Values.template.spec.serviceAccountName) }}
{{- $annotations := include "gha-runner-scale-set.effective-annotations" (dict "ctx" . "meta" $meta) | fromJson }}
apiVersion: "v1"
kind: "ServiceAccount"
metadata: {
  name: {{ include "gha-runner-scale-set.kubeModeServiceAccountName" . | toJson }},
  namespace: {{ include "gha-runner-scale-set.namespace" . | toJson }},
  {{- if $annotations }}
  annotations: {{ $annotations | toJson }},
  {{- end }}
  labels: {{ include "gha-runner-scale-set.effective-labels" (dict "ctx" . "meta" $meta) }},
  finalizers: ["actions.github.com/cleanup-protection"],
}
{{- end }}
