{{- $meta := and .Values.resourceMeta .Values.resourceMeta.managerRoleBinding }}
{{- $annotations := include "gha-runner-scale-set.effective-annotations" (dict "ctx" . "meta" $meta) | fromJson }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata: {
  name: {{ include "gha-runner-scale-set.managerRoleBindingName" . | toJson }},
  namespace: {{ include "gha-runner-scale-set.namespace" . | toJson }},
  labels: {{ include "gha-runner-scale-set.effective-labels" (dict "ctx" . "meta" $meta "component" "manager-role-binding") }},
  {{- if $annotations }}
  annotations: {{ $annotations | toJson }},
  {{- end }}
  finalizers: ["actions.github.com/cleanup-protection"],
}
roleRef: {
  apiGroup: "rbac.authorization.k8s.io",
  kind: "Role",
  name: {{ include "gha-runner-scale-set.managerRoleName" . | toJson }},
}
subjects: [{
  kind: "ServiceAccount",
  name: {{ include "gha-runner-scale-set.managerServiceAccountName" . | toJson }},
  namespace: {{ include "gha-runner-scale-set.managerServiceAccountNamespace" . | toJson }},
}]
