{{- $meta := and .Values.resourceMeta .Values.resourceMeta.noPermissionServiceAccount }}
{{- $containerMode := .Values.containerMode }}
{{- if and (ne $containerMode.type "kubernetes") (ne $containerMode.type "kubernetes-novolume") (not .Values.template.spec.serviceAccountName) }}
{{- $annotations := include "gha-runner-scale-set.effective-annotations" (dict "ctx" . "meta" $meta) | fromJson }}
apiVersion: "v1"
kind: "ServiceAccount"
metadata: {
  name: {{ include "gha-runner-scale-set.noPermissionServiceAccountName" . | toJson }},
  namespace: {{ include "gha-runner-scale-set.namespace" . | toJson }},
  labels: {{ include "gha-runner-scale-set.effective-labels" (dict "ctx" . "meta" $meta) }},
  {{- if $annotations }}
  annotations: {{ $annotations | toJson }},
  {{- end }}
  finalizers: ["actions.github.com/cleanup-protection"],
}
{{- end }}
