{{- if .Values.serviceAccount.create }}
apiVersion: "v1"
kind: "ServiceAccount"
metadata: {
  name: {{ include "gha-runner-scale-set-controller.serviceAccountName" . | toJson }},
  namespace: {{ include "gha-runner-scale-set-controller.namespace" . | toJson }},
  labels: {{ include "gha-runner-scale-set-controller.labels" . }},
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{ . | toJson }},
  {{- end }}
}
{{- end }}
